---
title: "Duvauchelle Population Dynamics"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.extra='',fig.pos="H",
                      fig.path = "./figs/",dpi = 300,fig.keep='last',dev='png')
knitr::opts_knit$set(root.dir='../results/',fig_path="./figs/")
```

```{r loadLibs, include=FALSE, echo=FALSE}
library(scales)
library(knitr)
library(dplyr)
library(magick)
library(tidyr)
library("googledrive")
```

```{r}
combdat<-read.csv("../data/cleanedCommunity.csv")
seasonCols<-c(Spring="coral",Summer="olivedrab3",Fall="gold",Winter="dodgerblue")
```


# Flounder

```{r}

flounder<-combdat[,grep("flounder",colnames(combdat))]
flounder[is.na(flounder)]<-0
flounder$tow<-rownames(combdat)

flounder$Date<-as.Date(
  paste0(
    gsub("^(\\d)$","0\\1",combdat$Date),
    gsub("^(\\d)$","0\\1",combdat$Month),
    combdat$Year),
  format = "%d%m%Y")
```

```{r}
plot(flounder$Date,flounder$flounder_below10mm)
plot(flounder$Date,flounder$flounder_10to20mm)
plot(flounder$Date,flounder$flounder_20to50mm)
plot(flounder$Date,flounder$flounder_above50mm)

```



```{r}
flounder$Season<-gsub("\\d+-(\\d+)-\\d+","\\1",flounder$Date)
flounder$Season[flounder$Season %in% c("09","10","11")]<-"Spring"
flounder$Season[flounder$Season %in% c("12","01","02")]<-"Summer"
flounder$Season[flounder$Season %in% c("03","04","05")]<-"Fall"
flounder$Season[flounder$Season %in% c("06","07","08")]<-"Winter"
```

```{r}
flounder_long <- gather(flounder, size, count, 1:4, factor_key=TRUE)
flounder_long$size<-as.factor(gsub("flounder_","",flounder_long$size))
levels(flounder_long$size)<-c("below10mm","10to20mm","20to50mm","above50mm")

```


```{r}
par(mfrow=c(2,2),mar=c(3,4,3.5,2),oma=c(3,2,1,2))
for(i in 1:length(seasonCols)){
  sdat<-flounder_long[flounder_long$Season %in% names(seasonCols)[i],]
  stripchart(sdat$count~sdat$size,
           vertical=TRUE,
           method="jitter",
           jitter=0.05,
           ylab="Number of fish",
           pch=1,
           frame.plot=FALSE,
           axes=FALSE,
           col=seasonCols[i],
           main= names(seasonCols)[i],
           cex.lab=1.2,
           ylim=c(0,50),
           cex=1.5)
  text(x=0.5:3.5,
       y= par("usr")[3] - 15,
       labels = levels(sdat$size),
       xpd = NA,
       srt = 35,
       cex=1.2)
  axis(2,las=2,cex=1.5)
}


```

GLMER Poisson counts by seasons 

```{r}
library(lme4)

flounderGLM<-glmer(flounder_long$count ~ flounder_long$Season*flounder_long$size + (1 | flounder_long$Date),
                   family = poisson)
```

While controlling for sampling dates, and accounting for size classes, flounder were most abundant in fall and least abundant in summer.  

# Pipefish

```{r driveDownload,eval=FALSE}
drive_dat<-drive_download("NZsyngnathids_measurements", 
                          path="../data/NZsyngnathids_measurements",
                          type = "csv",
                          overwrite=TRUE)
```
```{r readCSV}
body_dat<-read.csv("../data/NZsyngnathids_measurements.csv")
body_dat$ID<-gsub("(\\w{2})0(\\d{2})","\\1\\2",body_dat$ID)
```

```{r AvgVals}
body_dat$TotalLength_Avg<-rowMeans(body_dat[,grep("TotalLength",colnames(body_dat))],na.rm = TRUE)
body_dat$SVL_Avg<-rowMeans(body_dat[,grep("SVL",colnames(body_dat))],na.rm = TRUE)
body_dat$BodyWidth_Avg<-rowMeans(body_dat[,grep("BodyWidth",colnames(body_dat))],na.rm = TRUE)
body_dat$BodyDepth_Avg<-rowMeans(body_dat[,grep("BodyDepth",colnames(body_dat))],na.rm = TRUE)
body_dat$SnoutLength_Avg<-rowMeans(body_dat[,grep("SnoutLength",colnames(body_dat))],na.rm = TRUE)
body_dat$SnoutWidth_Avg<-rowMeans(body_dat[,c(grep("SnoutWidth",colnames(body_dat)),grep("SnoutDepth",colnames(body_dat)))],na.rm = TRUE)
body_dat$HeadLength_Avg<-rowMeans(body_dat[,grep("HeadLength",colnames(body_dat))],na.rm = TRUE)
```

```{r}
duv_traits<-body_dat[body_dat$LocationName=="Duvauchelle Bay",]

sni_dat<-combdat[,c("Day","towDist","Season","seagrass_cover",
                   grep("nigra",colnames(combdat),value = TRUE))]
sni_dat$total_snigra<-rowSums(sni_dat[,5:6])

sni_num<-as.data.frame(do.call(rbind,by(sni_dat,sni_dat$Day,function(dat){
  return(sum(dat$total_snigra))
},simplify = FALSE)))
colnames(sni_num)<-"totalN"

```

```{r}
library(lubridate)
sni_num$date<-ymd(rownames(sni_num))

duv_traits$date<-ymd(gsub(" NZDT","",strptime(duv_traits$DateSampled,format="%d-%b-%Y")))

db_num<-data.frame(measuredN=tapply(duv_traits$ID,as.factor(duv_traits$date),length))
db_num$date<-ymd(rownames(db_num))

sni_num<-merge(sni_num,db_num,by="date",all.x=TRUE)
sni_num$unmeasured<-sni_num$totalN-sni_num$measuredN
```



### S. nigra

```{r}
cnts<-as.data.frame.matrix(table(duv_traits$date,duv_traits$Sex))
colnames(cnts)[1]<-"juvenile"
cnts$date<-ymd(rownames(cnts))

cnts<-merge(sni_num,cnts,by="date",all.x=TRUE)
cnts[is.na(cnts)]<-0

```

```{r pipefishDat}
pipecounts<-rawdat[,c("Day","Season","towDist","seagrass_cover",
                      "leptonotus_below50mm","leptonotus_above50mm",
                      "s.nigra_below50mm","s.nigra_above50mm")]


stig_counts<-tapply(pipecounts$S_nigra,pipecounts$Month,sum)
lept_counts<-tapply(pipecounts$Leptonotus,pipecounts$Month,sum)

pipedat<-data.frame(month=names(stig_counts),
                    Snigra_total=stig_counts,
                    Lelevat_total=lept_counts)

pipedat$month<-c("Jan","Feb","Oct","Nov","Dec")
pipedat$Snigra_PregMale<-0
pipedat$Snigra_NonpMale<-0
pipedat$Snigra_Female<-0
pipedat$Snigra_Juvenile<-0

pipedat$Lelevat_PregMale<-0
pipedat$Lelevat_NonpMale<-0
pipedat$Lelevat_Female<-0
pipedat$Lelevat_Juvenile<-0


pipes$Month<-gsub("\\d\\d-(\\w+)-\\d+","\\1",pipes$date_tagged)

# s. nigra
snigra<-pipes[pipes$species=="S. nigra",]
sn_sextab<-table(snigra$Month,snigra$sex)
pipedat[pipedat$month %in% rownames(sn_sextab),
        "Snigra_Female"]<-sn_sextab[
          pipedat$month[pipedat$month %in% rownames(sn_sextab)],
          "female"]
sn_maltab<-table(snigra$Month,snigra$pregnancy_status)
pipedat[pipedat$month %in% rownames(sn_maltab),
        "Snigra_PregMale"]<-sn_maltab[
          pipedat$month[pipedat$month %in% rownames(sn_maltab)],
          "pregnant"]
pipedat[pipedat$month %in% rownames(sn_maltab),
        "Snigra_NonpMale"]<-sn_maltab[pipedat$month[
          pipedat$month %in% rownames(sn_maltab)],
          "not pregnant"]
pipedat$Snigra_Juvenile<-pipedat$Snigra_total-(
  pipedat$Snigra_PregMale+
    pipedat$Snigra_NonpMale+
    pipedat$Snigra_Female)

# l. elevatus
leleva<-pipes[pipes$species=="L. elevatus",]
le_sextab<-table(leleva$Month,leleva$sex)
pipedat[pipedat$month %in% rownames(le_sextab),
        "Lelevat_Female"]<-le_sextab[pipedat$month[
          pipedat$month %in% rownames(le_sextab)],"female"]
le_maltab<-table(leleva$Month,leleva$pregnancy_status)
pipedat[pipedat$month %in% rownames(le_maltab),
        "Lelevat_PregMale"]<-le_maltab[pipedat$month[
          pipedat$month %in% rownames(le_maltab)],"pregnant"]
pipedat[pipedat$month %in% rownames(le_maltab),
        "Lelevat_NonpMale"]<-le_maltab[pipedat$month[
          pipedat$month %in% rownames(le_maltab)],"not pregnant"]
pipedat$Lelevat_Juvenile<-pipedat$Lelevat_total-(
  pipedat$Lelevat_PregMale+
    pipedat$Lelevat_NonpMale+
    pipedat$Lelevat_Female)

```

```{r plotPipefish,fig.width=7,fig.height=6,fig.keep='high',dpi=300}
pipedat<-pipedat[match(c("Oct","Nov","Dec","Jan","Feb"),pipedat$month),]
colors<-c(fem="#fb9a99",juv="#33a02c",preg="#1f78b4",nonp="#a6cee3")

par(mfrow=c(3,1),mar=c(3,3,3,2),oma=c(2.5,3,2.5,1.5))
# all adults vs juveniles
plot(pipedat$Snigra_Juvenile+pipedat$Lelevat_Juvenile,
     xlab = "month",axes=FALSE,ylab="Number of Pipefish",
     pch=0,lty=3,cex=2,col=colors["juv"],ylim=c(0,12))
points(pipedat$Snigra_Juvenile+pipedat$Lelevat_Juvenile,
       type='l',lty=3,lwd=2,col=colors["juv"])
axis(1,labels = c("",pipedat$month),at=0:nrow(pipedat),pos=-.5)
axis(2,at=seq(-10,10),pos=0.85,las=1)
points((pipedat$Snigra_total-pipedat$Snigra_Juvenile)+
         (pipedat$Lelevat_total-pipedat$Lelevat_Juvenile),
       pch=5,col="dark grey",lty=1,cex=2)
points((pipedat$Snigra_total-pipedat$Snigra_Juvenile)+
         (pipedat$Lelevat_total-pipedat$Lelevat_Juvenile),
       type='l',col="dark grey",lty=1,lwd=2)
legend("topright",bty='n',c("Adults","Juveniles"),
       pch=c(5,0),lty=c(1,3),pt.cex=2,lwd=2,col=c("dark grey",colors["juv"]))
legend("topleft",legend = "All pipefish",text.font = 2,bty='n')

# S. nigra
plot(pipedat$Snigra_total,xlab = "month",axes=FALSE,ylab="Number of S. nigra",type = 'n')
axis(1,labels = c("",pipedat$month),at=0:nrow(pipedat),pos=-.5)
axis(2,at=seq(-10,10),pos=0.85,las=1)
# females
points(pipedat$Snigra_Female,pch=19,lty=1,cex=2,col=colors["fem"])
points(pipedat$Snigra_Female,type='l',lty=1,lwd=2,col=colors["fem"])
# males
points(pipedat$Snigra_PregMale,pch=25,bg=colors["preg"],col=colors["preg"],cex=2)
points(pipedat$Snigra_PregMale,type='l',lty=2,lwd=2,col=colors["preg"])
points(pipedat$Snigra_NonpMale,pch=25,bg=colors["nonp"],col=colors["nonp"],cex=2)
points(pipedat$Snigra_NonpMale,type='l',lty=2,lwd=2,col=colors["nonp"])
# juveniles
points(pipedat$Snigra_Juvenile,pch=0,lty=3,cex=2,col=colors["juv"])
points(pipedat$Snigra_Juvenile,type='l',lty=3,lwd=2,col=colors["juv"])
legend("topright",bty='n',ncol=2,
       c("Females","Juveniles","Pregnant Males","Non-pregnant males"),
       pch=c(19,0,25,25),lty=c(1,3,2,2),pt.cex=2,lwd=2,
       col=colors[c("fem","juv","preg","nonp")],
       bg=c(colors[c("fem","juv","preg")],"transparent"))
legend("topleft",legend =expression(italic("Stigmatopora nigra")),
       text.font = 2,bty='n')

# L. elevatus
plot(pipedat$Lelevat_total,xlab = "month",axes=FALSE,ylab="",type = 'n')
axis(1,labels = c("",pipedat$month),at=0:nrow(pipedat),pos=-.5)
axis(2,at=seq(-10,10),pos=0.85,las=1)
# females
points(pipedat$Lelevat_Female,pch=19,lty=1,cex=2,col=colors["fem"])
points(pipedat$Lelevat_Female,type='l',lty=1,lwd=2,col=colors["fem"])
# males
points(pipedat$Lelevat_PregMale,pch=25,bg=colors["preg"],col=colors["preg"],cex=2)
points(pipedat$Lelevat_PregMale,type='l',lty=2,lwd=2,col=colors["preg"])
points(pipedat$Lelevat_NonpMale,pch=25,bg=colors["nonp"],col=colors["nonp"],cex=2)
points(pipedat$Lelevat_NonpMale,type='l',lty=2,lwd=2,col=colors["nonp"])
# juveniles
points(pipedat$Lelevat_Juvenile,pch=0,lty=3,cex=2,col=colors["juv"])
points(pipedat$Lelevat_Juvenile,type='l',lty=3,lwd=2,col=colors["juv"])
legend("topright",bty='n',ncol=2,
       c("Females","Juveniles","Pregnant Males","Non-pregnant males"),
       pch=c(19,0,25,25),lty=c(1,3,2,2),pt.cex=2,lwd=2,
       col=colors[c("fem","juv","preg","nonp")],
       bg=c(colors[c("fem","juv","preg")],"transparent"))
legend("topleft",legend =expression(italic("Leptonotus elevatus")),
       text.font = 2,bty='n')
mtext("Number of pipefish",side=2,outer=TRUE)

```

